name: Create Release
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'The type of release. Must be major, minor or patch'
        required: true
jobs:
  create_release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      # Make sure we can lint before creating the release.
      - name: Cocoapods lint
        run: make cocoapods
      # Make sure we can build with Carthage before the release
      - name: Build and archive framework for Carthage users
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
        run: carthage build --no-skip-current && carthage archive
      - name: Create Release Commit
        env:
          GITHUB_CHANGELOG_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          OSS_PROJECT: PINRemoteImage
        run: |
          gem install github_changelog_generator
          Scripts/release.sh --${{ github.event.inputs.release-type }}
          git push origin HEAD
      - name: Tag Release
        run: Scripts/tag-release-branch.sh
      - name: Publish Release
        uses: actions/create-release@v1
        env:
          GITHUB_CHANGELOG_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          body_path: RELEASE_NOTES.md
          draft: false
      - name: Push to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push
      - name: Upload binary framework to release asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FRAMEWORK_NAME: PINRemoteImage
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./${{ env.FRAMEWORK_NAME }}.framework.zip
          asset_name: ${{ env.FRAMEWORK_NAME }}.framework.zip
          asset_content_type: application/zip

